### ISSUE TITLE
doesn't connect to UPTimeKuma in docker container

### ISSUE THREAD

**Issue by sdetweil** [MikeBishop/MMM-uptimekuma#1]
trying to connect, using the constructed status page url , using browser just spins..
axios get never returns from await

http://mac-mini:3001/api/status-page/default

![Snip20240223_2](https://github.com/MikeBishop/MMM-uptimekuma/assets/1498142/57e492d9-ce35-4d47-8bfa-95ed6394c249)
utk version 

Version: 1.23.11
Macos

**Comment by MikeBishop** [comment]
What does the browser show at `http://mac-mini:3001/status/default`? The browser tools (F12) might also give a hint.  In mine, I can see it querying the `api/status-page/heartbeat/default` path, for example:
![image](https://github.com/MikeBishop/MMM-uptimekuma/assets/4273797/70f1151c-70f3-4281-bacb-664fa58831ef)

**Comment by sdetweil** [comment]
the page is empty 
![Snip20240223_3](https://github.com/MikeBishop/MMM-uptimekuma/assets/1498142/9c635461-b27a-406e-88f7-306c6262b2ea)

only js 
![Snip20240223_4](https://github.com/MikeBishop/MMM-uptimekuma/assets/1498142/e64f3f77-2af1-4ddc-8654-a65aef7e954d)

**Comment by MikeBishop** [comment]
That looks like a UK issue more than this module -- I'd encourage you to check the network view in the debug tools to see whether something is failing to download. I'd wonder if JS is disabled in your browser, except that obviously you're able to load the UK dashboard properly.

**Comment by sdetweil** [comment]
i changed my docker container to map to port 80.. 
but really no change, dev tools shows error
for UK/status-page/default (module) 
```text 
web-client-content-script.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'animation' in undefined
    at Ye (web-client-content-script.js:2:49247)
    at 995 (web-client-content-script.js:2:49530)
    at n (web-client-content-script.js:2:182360)
    at 306 (web-client-content-script.js:2:152623)
    at n (web-client-content-script.js:2:182360)
    at web-client-content-script.js:2:197374
    at web-client-content-script.js:2:379018
    at web-client-content-script.js:2:379033
Ye @ web-client-content-script.js:2
995 @ web-client-content-script.js:2
n @ web-client-content-script.js:2
306 @ web-client-content-script.js:2
n @ web-client-content-script.js:2
(anonymous) @ web-client-content-script.js:2
(anonymous) @ web-client-content-script.js:2
(anonymous) @ web-client-content-script.js:2
onloadwff.js:71 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at s.<anonymous> (onloadwff.js:71:820251)
    at l (onloadwff.js:71:800922)
    at Object.next (onloadwff.js:71:800233)
    at n (onloadwff.js:71:799769)
```
for /status
```text
GET http://localhost/status 404 (Not Found)
```

like there is some config step I didn't do.. but I don't see any setup info for UK..

**Comment by sdetweil** [comment]
I stopped the container, deleted the mapped folder and restarted.. created new userid, and same.. not found for status

**Comment by sdetweil** [comment]
aha, I had to create a status page and add the monitors to expose to it

![Snip20240224_1](https://github.com/MikeBishop/MMM-uptimekuma/assets/1498142/e1f3aac2-5c64-4b2e-9b80-8c6b56a96a99)

then call to status-page worked
https://utka.xx.yy/api/status-page/default
```json
{"config":{"slug":"default","title":"default","description":null,"icon":"/icon.svg","theme":"auto","published":true,"showTags":false,"customCSS":"body {\n  \n}\n","footerText":null,"showPoweredBy":true,"googleAnalyticsId":null,"showCertificateExpiry":false},"incident":null,"publicGroupList":[{"id":1,"name":"Services","weight":1,"monitorList":[{"id":1,"name":"cnsearch arizona","sendUrl":1,"type":"http","url":"https://cnsearch.xx.yy"}]}],"maintenanceList":[]}
```

**Comment by sdetweil** [comment]
I opened UK issue
https://github.com/louislam/uptime-kuma/issues/4523

**Comment by sdetweil** [comment]
can close, just waiting  til you saw it.. thanks for your help

**Comment by MikeBishop** [comment]
Ah, I see. I should improve the docs to make it clear you need a status page created in UK for this to be able to read it.
